    - name: Running command na_elementsw_cluster_config
      include_tasks: tasks/na_elementsw_cluster_config_task.yml
      loop: "{{ na_elementsw_cluster_config }}"
      vars:
        req_cluster_config_hostname_01: '{{ item.hostname }}'
        req_cluster_config_password_01: '{{ item.password }}'
        req_cluster_config_username_01: '{{ item.username }}'
        #opt_cluster_config_enable_virtual_volumes_01: '{{ item.enable_virtual_volumes }}'
        #opt_cluster_config_encryption_at_rest_01: '{{ item.encryption_at_rest }}'
        #opt_cluster_config_modify_cluster_full_threshold_01: '{{ item.modify_cluster_full_threshold }}'
        #opt_cluster_config_set_ntp_info_01: '{{ item.set_ntp_info }}'
  
