    - name: Running command na_ontap_security_config
      include_tasks: tasks/na_ontap_security_config_task.yml
      loop: "{{ na_ontap_security_config }}"
      vars:
        req_security_config_hostname_01: '{{ item.hostname }}'
        #opt_security_config_cert_filepath_01: '{{ item.cert_filepath }}'
        #opt_security_config_feature_flags_01: '{{ item.feature_flags }}'
        #opt_security_config_http_port_01: '{{ item.http_port }}'
        #opt_security_config_https_01: '{{ item.https }}'
        #opt_security_config_is_fips_enabled_01: '{{ item.is_fips_enabled }}'
        #opt_security_config_key_filepath_01: '{{ item.key_filepath }}'
        #opt_security_config_name_01: '{{ item.name }}'
        #opt_security_config_ontapi_01: '{{ item.ontapi }}'
        #opt_security_config_password_01: '{{ item.password }}'
        #opt_security_config_supported_ciphers_01: '{{ item.supported_ciphers }}'
        #opt_security_config_supported_protocols_01: '{{ item.supported_protocols }}'
        #opt_security_config_use_rest_01: '{{ item.use_rest }}'
        #opt_security_config_username_01: '{{ item.username }}'
        #opt_security_config_validate_certs_01: '{{ item.validate_certs }}'
  
