---
- name: Running command azure_rm_netapp_account
  azure_rm_netapp_account:
    name: '{{ azure_rm_netapp_account_name_01 }}'
    resource_group: '{{ azure_rm_netapp_account_resource_group_01 }}'
    active_directories: '{{ azure_rm_netapp_account_active_directories_01  | default(omit)  }}'
    ad_user: '{{ azure_rm_netapp_account_ad_user_01  | default(omit)  }}'
    adfs_authority_url: '{{ azure_rm_netapp_account_adfs_authority_url_01  | default(omit)  }}'
    api_profile: '{{ azure_rm_netapp_account_api_profile_01  | default(omit)  }}'
    append_tags: '{{ azure_rm_netapp_account_append_tags_01  | default(omit)  }}'
    auth_source: '{{ azure_rm_netapp_account_auth_source_01  | default(omit)  }}'
    cert_validation_mode: '{{ azure_rm_netapp_account_cert_validation_mode_01  | default(omit)  }}'
    client_id: '{{ azure_rm_netapp_account_client_id_01  | default(omit)  }}'
    cloud_environment: '{{ azure_rm_netapp_account_cloud_environment_01  | default(omit)  }}'
    debug: '{{ azure_rm_netapp_account_debug_01  | default(omit)  }}'
    location: '{{ azure_rm_netapp_account_location_01  | default(omit)  }}'
    log_mode: '{{ azure_rm_netapp_account_log_mode_01  | default(omit)  }}'
    log_path: '{{ azure_rm_netapp_account_log_path_01  | default(omit)  }}'
    profile: '{{ azure_rm_netapp_account_profile_01  | default(omit)  }}'
    secret: '{{ azure_rm_netapp_account_secret_01  | default(omit)  }}'
    state: '{{ azure_rm_netapp_account_state_01  | default(omit)  }}'
    subscription_id: '{{ azure_rm_netapp_account_subscription_id_01  | default(omit)  }}'
    tags: '{{ azure_rm_netapp_account_tags_01  | default(omit)  }}'
    tenant: '{{ azure_rm_netapp_account_tenant_01  | default(omit)  }}'
  register: results
