---
- name: Running command na_ontap_fcp
  na_ontap_fcp:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    #validate_certs: "{{ validate_certs }}"
    vserver: '{{ item.req_fcp_vserver_01 }}'
    feature_flags: '{{ item.opt_fcp_feature_flags_01 | default(omit) }}'
    name: '{{ item.opt_fcp_name_01 | default(omit) }}'
    state: '{{ item.opt_fcp_state_01 | default(omit) }}'
    status: '{{ item.opt_fcp_status_01 | default(omit) }}'
  register: results
