---
- name: Running command na_ontap_firewall_policy
  na_ontap_firewall_policy:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    #validate_certs: "{{ validate_certs }}"
    allow_list: '{{ item.opt_firewall_policy_allow_list_01 | default(omit) }}'
    enable: '{{ item.opt_firewall_policy_enable_01 | default(omit) }}'
    feature_flags: '{{ item.opt_firewall_policy_feature_flags_01 | default(omit) }}'
    logging: '{{ item.opt_firewall_policy_logging_01 | default(omit) }}'
    name: '{{ item.opt_firewall_policy_name_01 | default(omit) }}'
    node: '{{ item.opt_firewall_policy_node_01 | default(omit) }}'
    policy: '{{ item.opt_firewall_policy_policy_01 | default(omit) }}'
    service: '{{ item.opt_firewall_policy_service_01 | default(omit) }}'
    state: '{{ item.opt_firewall_policy_state_01 | default(omit) }}'
    vserver: '{{ item.opt_firewall_policy_vserver_01 | default(omit) }}'
  register: results
