---
- name: Running command na_ontap_cluster_ha
  na_ontap_cluster_ha:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    #validate_certs: "{{ validate_certs }}"
    feature_flags: '{{ item.opt_cluster_ha_feature_flags_01 | default(omit) }}'
    name: '{{ item.opt_cluster_ha_name_01 | default(omit) }}'
    state: '{{ item.opt_cluster_ha_state_01 | default(omit) }}'
  register: results
