---
- name: Running command na_ontap_security_key_manager
  na_ontap_security_key_manager:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    #validate_certs: "{{ validate_certs }}"
    ip_address: '{{ item.req_security_key_manager_ip_address_01 }}'
    feature_flags: '{{ item.opt_security_key_manager_feature_flags_01 | default(omit) }}'
    name: '{{ item.opt_security_key_manager_name_01 | default(omit) }}'
    node: '{{ item.opt_security_key_manager_node_01 | default(omit) }}'
    state: '{{ item.opt_security_key_manager_state_01 | default(omit) }}'
    tcp_port: '{{ item.opt_security_key_manager_tcp_port_01 | default(omit) }}'
  register: results
