---
- name: Running command na_ontap_lun_copy
  na_ontap_lun_copy:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    #validate_certs: "{{ validate_certs }}"
    destination_path: '{{ item.req_lun_copy_destination_path_01 }}'
    destination_vserver: '{{ item.req_lun_copy_destination_vserver_01 }}'
    source_path: '{{ item.req_lun_copy_source_path_01 }}'
    feature_flags: '{{ item.opt_lun_copy_feature_flags_01 | default(omit) }}'
    name: '{{ item.opt_lun_copy_name_01 | default(omit) }}'
    source_vserver: '{{ item.opt_lun_copy_source_vserver_01 | default(omit) }}'
    state: '{{ item.opt_lun_copy_state_01 | default(omit) }}'
  register: results
