---
- name: Running command na_ontap_node
  na_ontap_node:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    #validate_certs: "{{ validate_certs }}"
    from_name: '{{ item.req_node_from_name_01 }}'
    name: '{{ item.req_node_name_01 }}'
    feature_flags: '{{ item.opt_node_feature_flags_01 | default(omit) }}'
  register: results
