---
- name: Running command na_ontap_qtree
  na_ontap_qtree:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    #validate_certs: "{{ validate_certs }}"
    flexvol_name: '{{ item.req_qtree_flexvol_name_01 }}'
    name: '{{ item.req_qtree_name_01 }}'
    vserver: '{{ item.req_qtree_vserver_01 }}'
    export_policy: '{{ item.opt_qtree_export_policy_01 | default(omit) }}'
    feature_flags: '{{ item.opt_qtree_feature_flags_01 | default(omit) }}'
    from_name: '{{ item.opt_qtree_from_name_01 | default(omit) }}'
    oplocks: '{{ item.opt_qtree_oplocks_01 | default(omit) }}'
    security_style: '{{ item.opt_qtree_security_style_01 | default(omit) }}'
    state: '{{ item.opt_qtree_state_01 | default(omit) }}'
    unix_permissions: '{{ item.opt_qtree_unix_permissions_01 | default(omit) }}'
  register: results
