---
- name: Running command na_ontap_job_schedule
  na_ontap_job_schedule:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    #validate_certs: "{{ validate_certs }}"
    name: '{{ item.req_job_schedule_name_01 }}'
    feature_flags: '{{ item.opt_job_schedule_feature_flags_01 | default(omit) }}'
    job_days_of_month: '{{ item.opt_job_schedule_job_days_of_month_01 | default(omit) }}'
    job_days_of_week: '{{ item.opt_job_schedule_job_days_of_week_01 | default(omit) }}'
    job_hours: '{{ item.opt_job_schedule_job_hours_01 | default(omit) }}'
    job_minutes: '{{ item.opt_job_schedule_job_minutes_01 | default(omit) }}'
    job_months: '{{ item.opt_job_schedule_job_months_01 | default(omit) }}'
    state: '{{ item.opt_job_schedule_state_01 | default(omit) }}'
  register: results
