---
- name: Running command na_ontap_dns
  na_ontap_dns:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    #validate_certs: "{{ validate_certs }}"
    vserver: '{{ item.req_dns_vserver_01 }}'
    domains: '{{ item.opt_dns_domains_01 | default(omit) }}'
    feature_flags: '{{ item.opt_dns_feature_flags_01 | default(omit) }}'
    name: '{{ item.opt_dns_name_01 | default(omit) }}'
    nameservers: '{{ item.opt_dns_nameservers_01 | default(omit) }}'
    skip_validation: '{{ item.opt_dns_skip_validation_01 | default(omit) }}'
    state: '{{ item.opt_dns_state_01 | default(omit) }}'
  register: results
