---
- name: Running command na_ontap_autosupport_invoke
  na_ontap_autosupport_invoke:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    #validate_certs: "{{ validate_certs }}"
    feature_flags: '{{ item.opt_autosupport_invoke_feature_flags_01 | default(omit) }}'
    message: '{{ item.opt_autosupport_invoke_message_01 | default(omit) }}'
    name: '{{ item.opt_autosupport_invoke_name_01 | default(omit) }}'
    type: '{{ item.opt_autosupport_invoke_type_01 | default(omit) }}'
    uri: '{{ item.opt_autosupport_invoke_uri_01 | default(omit) }}'
  register: results
