---
- name: Running command na_ontap_iscsi_security
  na_ontap_iscsi_security:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    #validate_certs: "{{ validate_certs }}"
    initiator: '{{ item.req_iscsi_security_initiator_01 }}'
    vserver: '{{ item.req_iscsi_security_vserver_01 }}'
    address_ranges: '{{ item.opt_iscsi_security_address_ranges_01 | default(omit) }}'
    auth_type: '{{ item.opt_iscsi_security_auth_type_01 | default(omit) }}'
    feature_flags: '{{ item.opt_iscsi_security_feature_flags_01 | default(omit) }}'
    inbound_password: '{{ item.opt_iscsi_security_inbound_password_01 | default(omit) }}'
    inbound_username: '{{ item.opt_iscsi_security_inbound_username_01 | default(omit) }}'
    name: '{{ item.opt_iscsi_security_name_01 | default(omit) }}'
    outbound_password: '{{ item.opt_iscsi_security_outbound_password_01 | default(omit) }}'
    outbound_username: '{{ item.opt_iscsi_security_outbound_username_01 | default(omit) }}'
    state: '{{ item.opt_iscsi_security_state_01 | default(omit) }}'
  register: results
