---
- name: Running command na_ontap_volume_autosize
  na_ontap_volume_autosize:
    hostname: "{{{{ netapp_hostname }}}}"
    username: "{{{{ netapp_username }}}}"
    password: "{{{{ netapp_password }}}}"
    https: "{{{{ netapp_https | default(omit) }}}}"
    port: "{{{{ netapp_port | default(omit) }}}}"
    validate_certs: "{{{{ validate_certs | default(false) }}}}"
    volume: '{{ req_volume_autosize_volume }}'
    vserver: '{{ req_volume_autosize_vserver }}'
    feature_flags: '{{ opt_volume_autosize_feature_flags | default(omit) }}'
    grow_threshold_percent: '{{ opt_volume_autosize_grow_threshold_percent | default(omit) }}'
    increment_size: '{{ opt_volume_autosize_increment_size | default(omit) }}'
    maximum_size: '{{ opt_volume_autosize_maximum_size | default(omit) }}'
    minimum_size: '{{ opt_volume_autosize_minimum_size | default(omit) }}'
    mode: '{{ opt_volume_autosize_mode | default(omit) }}'
    name: '{{ opt_volume_autosize_name | default(omit) }}'
    reset: '{{ opt_volume_autosize_reset | default(omit) }}'
    shrink_threshold_percent: '{{ opt_volume_autosize_shrink_threshold_percent | default(omit) }}'
  register: results
