---
- name: Running command na_ontap_vserver_peer
  na_ontap_vserver_peer:
    hostname: "{{{{ netapp_hostname }}}}"
    username: "{{{{ netapp_username }}}}"
    password: "{{{{ netapp_password }}}}"
    https: "{{{{ netapp_https | default(omit) }}}}"
    port: "{{{{ netapp_port | default(omit) }}}}"
    validate_certs: "{{{{ validate_certs | default(false) }}}}"
    applications: '{{ opt_vserver_peer_applications | default(omit) }}'
    dest_hostname: '{{ opt_vserver_peer_dest_hostname | default(omit) }}'
    dest_password: '{{ opt_vserver_peer_dest_password | default(omit) }}'
    dest_username: '{{ opt_vserver_peer_dest_username | default(omit) }}'
    feature_flags: '{{ opt_vserver_peer_feature_flags | default(omit) }}'
    name: '{{ opt_vserver_peer_name | default(omit) }}'
    peer_cluster: '{{ opt_vserver_peer_peer_cluster | default(omit) }}'
    peer_vserver: '{{ opt_vserver_peer_peer_vserver | default(omit) }}'
    state: '{{ opt_vserver_peer_state | default(omit) }}'
    vserver: '{{ opt_vserver_peer_vserver | default(omit) }}'
  register: results
