---
- name: Running command na_ontap_snapshot
  na_ontap_snapshot:
    hostname: "{{{{ netapp_hostname }}}}"
    username: "{{{{ netapp_username }}}}"
    password: "{{{{ netapp_password }}}}"
    https: "{{{{ netapp_https | default(omit) }}}}"
    port: "{{{{ netapp_port | default(omit) }}}}"
    validate_certs: "{{{{ validate_certs | default(false) }}}}"
    snapshot: '{{ req_snapshot_snapshot }}'
    volume: '{{ req_snapshot_volume }}'
    vserver: '{{ req_snapshot_vserver }}'
    async_bool: '{{ opt_snapshot_async_bool | default(omit) }}'
    comment: '{{ opt_snapshot_comment | default(omit) }}'
    from_name: '{{ opt_snapshot_from_name | default(omit) }}'
    ignore_owners: '{{ opt_snapshot_ignore_owners | default(omit) }}'
    name: '{{ opt_snapshot_name | default(omit) }}'
    snapmirror_label: '{{ opt_snapshot_snapmirror_label | default(omit) }}'
    snapshot_instance_uuid: '{{ opt_snapshot_snapshot_instance_uuid | default(omit) }}'
    state: '{{ opt_snapshot_state | default(omit) }}'
  register: results
