---
- name: Running command na_ontap_snapmirror
  na_ontap_snapmirror:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: "{{ netapp_https | default(omit) }}"
    port: "{{ netapp_port | default(omit) }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    connection_type: '{{ opt_snapmirror_connection_type_01 | default(omit) }}'
    destination_path: '{{ opt_snapmirror_destination_path_01 | default(omit) }}'
    destination_volume: '{{ opt_snapmirror_destination_volume_01 | default(omit) }}'
    destination_vserver: '{{ opt_snapmirror_destination_vserver_01 | default(omit) }}'
    feature_flags: '{{ opt_snapmirror_feature_flags_01 | default(omit) }}'
    identity_preserve: '{{ opt_snapmirror_identity_preserve_01 | default(omit) }}'
    initialize: '{{ opt_snapmirror_initialize_01 | default(omit) }}'
    max_transfer_rate: '{{ opt_snapmirror_max_transfer_rate_01 | default(omit) }}'
    policy: '{{ opt_snapmirror_policy_01 | default(omit) }}'
    relationship_info_only: '{{ opt_snapmirror_relationship_info_only_01 | default(omit) }}'
    relationship_state: '{{ opt_snapmirror_relationship_state_01 | default(omit) }}'
    relationship_type: '{{ opt_snapmirror_relationship_type_01 | default(omit) }}'
    schedule: '{{ opt_snapmirror_schedule_01 | default(omit) }}'
    source_hostname: '{{ opt_snapmirror_source_hostname_01 | default(omit) }}'
    source_password: '{{ opt_snapmirror_source_password_01 | default(omit) }}'
    source_path: '{{ opt_snapmirror_source_path_01 | default(omit) }}'
    source_username: '{{ opt_snapmirror_source_username_01 | default(omit) }}'
    source_volume: '{{ opt_snapmirror_source_volume_01 | default(omit) }}'
    source_vserver: '{{ opt_snapmirror_source_vserver_01 | default(omit) }}'
    state: '{{ opt_snapmirror_state_01 | default(omit) }}'
    update: '{{ opt_snapmirror_update_01 | default(omit) }}'
  register: results
