---
- name: Running command na_ontap_cluster_peer
  na_ontap_cluster_peer:
    hostname: "{{{{ netapp_hostname }}}}"
    username: "{{{{ netapp_username }}}}"
    password: "{{{{ netapp_password }}}}"
    https: "{{{{ netapp_https | default(omit) }}}}"
    port: "{{{{ netapp_port | default(omit) }}}}"
    validate_certs: "{{{{ validate_certs | default(false) }}}}"
    dest_hostname: '{{ req_cluster_peer_dest_hostname }}'
    dest_cluster_name: '{{ opt_cluster_peer_dest_cluster_name | default(omit) }}'
    dest_intercluster_lifs: '{{ opt_cluster_peer_dest_intercluster_lifs | default(omit) }}'
    dest_password: '{{ opt_cluster_peer_dest_password | default(omit) }}'
    dest_username: '{{ opt_cluster_peer_dest_username | default(omit) }}'
    encryption_protocol_proposed: '{{ opt_cluster_peer_encryption_protocol_proposed | default(omit) }}'
    feature_flags: '{{ opt_cluster_peer_feature_flags | default(omit) }}'
    name: '{{ opt_cluster_peer_name | default(omit) }}'
    passphrase: '{{ opt_cluster_peer_passphrase | default(omit) }}'
    source_cluster_name: '{{ opt_cluster_peer_source_cluster_name | default(omit) }}'
    source_intercluster_lifs: '{{ opt_cluster_peer_source_intercluster_lifs | default(omit) }}'
    state: '{{ opt_cluster_peer_state | default(omit) }}'
  register: results
