---
- name: Running command na_ontap_net_vlan
  na_ontap_net_vlan:
    hostname: "{{{{ netapp_hostname }}}}"
    username: "{{{{ netapp_username }}}}"
    password: "{{{{ netapp_password }}}}"
    https: "{{{{ netapp_https | default(omit) }}}}"
    port: "{{{{ netapp_port | default(omit) }}}}"
    validate_certs: "{{{{ validate_certs | default(false) }}}}"
    node: '{{ req_net_vlan_node }}'
    parent_interface: '{{ req_net_vlan_parent_interface }}'
    vlanid: '{{ req_net_vlan_vlanid }}'
    name: '{{ opt_net_vlan_name | default(omit) }}'
    state: '{{ opt_net_vlan_state | default(omit) }}'
  register: results
