---
- name: Running command na_ontap_license
  na_ontap_license:
    hostname: "{{{{ netapp_hostname }}}}"
    username: "{{{{ netapp_username }}}}"
    password: "{{{{ netapp_password }}}}"
    https: "{{{{ netapp_https | default(omit) }}}}"
    port: "{{{{ netapp_port | default(omit) }}}}"
    validate_certs: "{{{{ validate_certs | default(false) }}}}"
    license_codes: '{{ opt_license_license_codes | default(omit) }}'
    license_names: '{{ opt_license_license_names | default(omit) }}'
    name: '{{ opt_license_name | default(omit) }}'
    remove_expired: '{{ opt_license_remove_expired | default(omit) }}'
    remove_unused: '{{ opt_license_remove_unused | default(omit) }}'
    serial_number: '{{ opt_license_serial_number | default(omit) }}'
    state: '{{ opt_license_state | default(omit) }}'
  register: results
