---
- name: Running command na_ontap_ucadapter
  na_ontap_ucadapter:
    hostname: "{{{{ netapp_hostname }}}}"
    username: "{{{{ netapp_username }}}}"
    password: "{{{{ netapp_password }}}}"
    https: "{{{{ netapp_https | default(omit) }}}}"
    port: "{{{{ netapp_port | default(omit) }}}}"
    validate_certs: "{{{{ validate_certs | default(false) }}}}"
    adapter_name: '{{ req_ucadapter_adapter_name }}'
    node_name: '{{ req_ucadapter_node_name }}'
    feature_flags: '{{ opt_ucadapter_feature_flags | default(omit) }}'
    mode: '{{ opt_ucadapter_mode | default(omit) }}'
    name: '{{ opt_ucadapter_name | default(omit) }}'
    state: '{{ opt_ucadapter_state | default(omit) }}'
    type: '{{ opt_ucadapter_type | default(omit) }}'
  register: results
