---
- name: Running command na_ontap_aggregate
  na_ontap_aggregate:
    hostname: "{{{{ netapp_hostname }}}}"
    username: "{{{{ netapp_username }}}}"
    password: "{{{{ netapp_password }}}}"
    https: "{{{{ netapp_https | default(omit) }}}}"
    port: "{{{{ netapp_port | default(omit) }}}}"
    validate_certs: "{{{{ validate_certs | default(false) }}}}"
    name: '{{ req_aggregate_name }}'
    disk_count: '{{ opt_aggregate_disk_count | default(omit) }}'
    disk_size: '{{ opt_aggregate_disk_size | default(omit) }}'
    disk_type: '{{ opt_aggregate_disk_type | default(omit) }}'
    disks: '{{ opt_aggregate_disks | default(omit) }}'
    from_name: '{{ opt_aggregate_from_name | default(omit) }}'
    is_mirrored: '{{ opt_aggregate_is_mirrored | default(omit) }}'
    mirror_disks: '{{ opt_aggregate_mirror_disks | default(omit) }}'
    nodes: '{{ opt_aggregate_nodes | default(omit) }}'
    raid_size: '{{ opt_aggregate_raid_size | default(omit) }}'
    raid_type: '{{ opt_aggregate_raid_type | default(omit) }}'
    service_state: '{{ opt_aggregate_service_state | default(omit) }}'
    spare_pool: '{{ opt_aggregate_spare_pool | default(omit) }}'
    state: '{{ opt_aggregate_state | default(omit) }}'
    time_out: '{{ opt_aggregate_time_out | default(omit) }}'
    unmount_volumes: '{{ opt_aggregate_unmount_volumes | default(omit) }}'
    wait_for_online: '{{ opt_aggregate_wait_for_online | default(omit) }}'
  register: results
