---
- name: Running command na_ontap_firmware_upgrade
  na_ontap_firmware_upgrade:
    hostname: "{{{{ netapp_hostname }}}}"
    username: "{{{{ netapp_username }}}}"
    password: "{{{{ netapp_password }}}}"
    https: "{{{{ netapp_https | default(omit) }}}}"
    port: "{{{{ netapp_port | default(omit) }}}}"
    validate_certs: "{{{{ validate_certs | default(false) }}}}"
    clear_logs: '{{ opt_firmware_upgrade_clear_logs_01 | default(omit) }}'
    disk_fw: '{{ opt_firmware_upgrade_disk_fw_01 | default(omit) }}'
    fail_on_502_error: '{{ opt_firmware_upgrade_fail_on_502_error_01 | default(omit) }}'
    feature_flags: '{{ opt_firmware_upgrade_feature_flags_01 | default(omit) }}'
    firmware_type: '{{ opt_firmware_upgrade_firmware_type_01 | default(omit) }}'
    force_disruptive_update: '{{ opt_firmware_upgrade_force_disruptive_update_01 | default(omit) }}'
    install_baseline_image: '{{ opt_firmware_upgrade_install_baseline_image_01 | default(omit) }}'
    name: '{{ opt_firmware_upgrade_name_01 | default(omit) }}'
    node: '{{ opt_firmware_upgrade_node_01 | default(omit) }}'
    package: '{{ opt_firmware_upgrade_package_01 | default(omit) }}'
    package_url: '{{ opt_firmware_upgrade_package_url_01 | default(omit) }}'
    reboot_sp: '{{ opt_firmware_upgrade_reboot_sp_01 | default(omit) }}'
    rename_package: '{{ opt_firmware_upgrade_rename_package_01 | default(omit) }}'
    replace_package: '{{ opt_firmware_upgrade_replace_package_01 | default(omit) }}'
    shelf_module_fw: '{{ opt_firmware_upgrade_shelf_module_fw_01 | default(omit) }}'
    state: '{{ opt_firmware_upgrade_state_01 | default(omit) }}'
    update_type: '{{ opt_firmware_upgrade_update_type_01 | default(omit) }}'
  register: results
