---
- name: Running command na_ontap_vscan_on_demand_task
  na_ontap_vscan_on_demand_task:
    hostname: "{{{{ netapp_hostname }}}}"
    username: "{{{{ netapp_username }}}}"
    password: "{{{{ netapp_password }}}}"
    https: "{{{{ netapp_https | default(omit) }}}}"
    port: "{{{{ netapp_port | default(omit) }}}}"
    validate_certs: "{{{{ validate_certs | default(false) }}}}"
    task_name: '{{ req_vscan_on_demand_task_task_name }}'
    vserver: '{{ req_vscan_on_demand_task_vserver }}'
    cross_junction: '{{ opt_vscan_on_demand_task_cross_junction | default(omit) }}'
    directory_recursion: '{{ opt_vscan_on_demand_task_directory_recursion | default(omit) }}'
    feature_flags: '{{ opt_vscan_on_demand_task_feature_flags | default(omit) }}'
    file_ext_to_exclude: '{{ opt_vscan_on_demand_task_file_ext_to_exclude | default(omit) }}'
    file_ext_to_include: '{{ opt_vscan_on_demand_task_file_ext_to_include | default(omit) }}'
    max_file_size: '{{ opt_vscan_on_demand_task_max_file_size | default(omit) }}'
    name: '{{ opt_vscan_on_demand_task_name | default(omit) }}'
    paths_to_exclude: '{{ opt_vscan_on_demand_task_paths_to_exclude | default(omit) }}'
    report_directory: '{{ opt_vscan_on_demand_task_report_directory | default(omit) }}'
    report_log_level: '{{ opt_vscan_on_demand_task_report_log_level | default(omit) }}'
    request_timeout: '{{ opt_vscan_on_demand_task_request_timeout | default(omit) }}'
    scan_files_with_no_ext: '{{ opt_vscan_on_demand_task_scan_files_with_no_ext | default(omit) }}'
    scan_paths: '{{ opt_vscan_on_demand_task_scan_paths | default(omit) }}'
    scan_priority: '{{ opt_vscan_on_demand_task_scan_priority | default(omit) }}'
    schedule: '{{ opt_vscan_on_demand_task_schedule | default(omit) }}'
    state: '{{ opt_vscan_on_demand_task_state | default(omit) }}'
  register: results
