---
- name: Running command na_ontap_fpolicy_status
  na_ontap_fpolicy_status:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username  | default(omit)  }}"
    password: "{{ netapp_password  | default(omit)  }}"
    cert_filepath: "{{ netapp_cert_filepath  | default(omit)  }}"
    key_filepath: "{{ netapp_key_filepath  | default(omit)  }}"
    https: "{{ netapp_https | default(true) }}"
    port: "{{ netapp_port  | default(omit)  }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    http_port: "{{ opt_lun_map_http_port_01  | default(omit)  }}"
    ontapi: "{{ opt_lun_map_ontapi_01  | default(omit)  }}"
    use_rest: "{{ opt_lun_map_use_rest_01  | default(omit)  }}"
    policy_name: '{{ req_fpolicy_status_policy_name_01 }}'
    vserver: '{{ req_fpolicy_status_vserver_01 }}'
    feature_flags: '{{ opt_fpolicy_status_feature_flags_01  | default(omit)  }}'
    sequence_number: '{{ opt_fpolicy_status_sequence_number_01  | default(omit)  }}'
    state: '{{ opt_fpolicy_status_state_01  | default(omit)  }}'
  register: results
