
    #vars:
# Section: na_ontap_security_config:
    # netapp_hostname: "" 
    # netapp_username: "" 
    # netapp_password: "" 
    # netapp_https: "True" 
    # netapp_port: "443" 
    # validate_certs: "false"
    req_security_config_hostname_01: ' '
    #opt_security_config_cert_filepath_01: ' '
    #opt_security_config_feature_flags_01: ' '
    #opt_security_config_http_port_01: ' '
    #opt_security_config_https_01: ' '
    #opt_security_config_is_fips_enabled_01: ' '
    #opt_security_config_key_filepath_01: ' '
    #opt_security_config_name_01: ' '
    #opt_security_config_ontapi_01: ' '
    #opt_security_config_password_01: ' '
    #opt_security_config_supported_ciphers_01: ' '
    #opt_security_config_supported_protocols_01: ' '
    #opt_security_config_use_rest_01: ' '
    #opt_security_config_username_01: ' '
    #opt_security_config_validate_certs_01: ' '
  
