---
- name: Running command na_elementsw_snapshot
  na_elementsw_snapshot:
    account_id: '{{ req_snapshot_account_id_01 }}'
    src_volume_id: '{{ req_snapshot_src_volume_id_01 }}'
    enable_remote_replication: '{{ opt_snapshot_enable_remote_replication_01  | default(omit)  }}'
    expiration_time: '{{ opt_snapshot_expiration_time_01  | default(omit)  }}'
    name: '{{ opt_snapshot_name_01  | default(omit)  }}'
    retention: '{{ opt_snapshot_retention_01  | default(omit)  }}'
    snap_mirror_label: '{{ opt_snapshot_snap_mirror_label_01  | default(omit)  }}'
    src_snapshot_id: '{{ opt_snapshot_src_snapshot_id_01  | default(omit)  }}'
    state: '{{ opt_snapshot_state_01  | default(omit)  }}'
  register: results
