---
- name: Running command na_elementsw_volume
  na_elementsw_volume:
    account_id: '{{ req_volume_account_id_01 }}'
    name: '{{ req_volume_name_01 }}'
    access: '{{ opt_volume_access_01  | default(omit)  }}'
    attributes: '{{ opt_volume_attributes_01  | default(omit)  }}'
    enable512e: '{{ opt_volume_enable512e_01  | default(omit)  }}'
    qos: '{{ opt_volume_qos_01  | default(omit)  }}'
    qos_policy_name: '{{ opt_volume_qos_policy_name_01  | default(omit)  }}'
    size: '{{ opt_volume_size_01  | default(omit)  }}'
    size_unit: '{{ opt_volume_size_unit_01  | default(omit)  }}'
    state: '{{ opt_volume_state_01  | default(omit)  }}'
  register: results
