---
- name: Running command na_elementsw_cluster_pair
  na_elementsw_cluster_pair:
    dest_mvip: '{{ req_cluster_pair_dest_mvip_01 }}'
    dest_password: '{{ opt_cluster_pair_dest_password_01  | default(omit)  }}'
    dest_username: '{{ opt_cluster_pair_dest_username_01  | default(omit)  }}'
    state: '{{ opt_cluster_pair_state_01  | default(omit)  }}'
  register: results
