---
- name: Running command na_elementsw_backup
  na_elementsw_backup:
    dest_volume_id: '{{ req_backup_dest_volume_id_01 }}'
    src_volume_id: '{{ req_backup_src_volume_id_01 }}'
    dest_hostname: '{{ opt_backup_dest_hostname_01  | default(omit)  }}'
    dest_password: '{{ opt_backup_dest_password_01  | default(omit)  }}'
    dest_username: '{{ opt_backup_dest_username_01  | default(omit)  }}'
    format: '{{ opt_backup_format_01  | default(omit)  }}'
    script: '{{ opt_backup_script_01  | default(omit)  }}'
    script_parameters: '{{ opt_backup_script_parameters_01  | default(omit)  }}'
  register: results
