---
- name: Running command na_elementsw_node
  na_elementsw_node:
    node_ids: '{{ req_node_node_ids_01 }}'
    cluster_name: '{{ opt_node_cluster_name_01  | default(omit)  }}'
    preset_only: '{{ opt_node_preset_only_01  | default(omit)  }}'
    state: '{{ opt_node_state_01  | default(omit)  }}'
  register: results
