---
- name: Running command na_elementsw_volume_clone
  na_elementsw_volume_clone:
    account_id: '{{ req_volume_clone_account_id_01 }}'
    name: '{{ req_volume_clone_name_01 }}'
    src_volume_id: '{{ req_volume_clone_src_volume_id_01 }}'
    access: '{{ opt_volume_clone_access_01  | default(omit)  }}'
    attributes: '{{ opt_volume_clone_attributes_01  | default(omit)  }}'
    size: '{{ opt_volume_clone_size_01  | default(omit)  }}'
    size_unit: '{{ opt_volume_clone_size_unit_01  | default(omit)  }}'
    src_snapshot_id: '{{ opt_volume_clone_src_snapshot_id_01  | default(omit)  }}'
  register: results
