---
- name: Running command na_elementsw_account
  na_elementsw_account:
    element_username: '{{ req_account_element_username_01 }}'
    attributes: '{{ opt_account_attributes_01  | default(omit)  }}'
    from_name: '{{ opt_account_from_name_01  | default(omit)  }}'
    initiator_secret: '{{ opt_account_initiator_secret_01  | default(omit)  }}'
    state: '{{ opt_account_state_01  | default(omit)  }}'
    status: '{{ opt_account_status_01  | default(omit)  }}'
    target_secret: '{{ opt_account_target_secret_01  | default(omit)  }}'
  register: results
