---
- name: Running command na_elementsw_vlan
  na_elementsw_vlan:
    vlan_tag: '{{ req_vlan_vlan_tag_01 }}'
    address_blocks: '{{ opt_vlan_address_blocks_01  | default(omit)  }}'
    attributes: '{{ opt_vlan_attributes_01  | default(omit)  }}'
    gateway: '{{ opt_vlan_gateway_01  | default(omit)  }}'
    name: '{{ opt_vlan_name_01  | default(omit)  }}'
    namespace: '{{ opt_vlan_namespace_01  | default(omit)  }}'
    netmask: '{{ opt_vlan_netmask_01  | default(omit)  }}'
    state: '{{ opt_vlan_state_01  | default(omit)  }}'
    svip: '{{ opt_vlan_svip_01  | default(omit)  }}'
  register: results
