---
- name: Running command na_elementsw_cluster_config
  na_elementsw_cluster_config:
    enable_virtual_volumes: '{{ opt_cluster_config_enable_virtual_volumes_01  | default(omit)  }}'
    encryption_at_rest: '{{ opt_cluster_config_encryption_at_rest_01  | default(omit)  }}'
    modify_cluster_full_threshold: '{{ opt_cluster_config_modify_cluster_full_threshold_01  | default(omit)  }}'
    set_ntp_info: '{{ opt_cluster_config_set_ntp_info_01  | default(omit)  }}'
  register: results
