---
- name: Running command na_cloudmanager_info
  na_cloudmanager_info:
    client_id: '{{ na_cloudmanager_info_client_id_01 }}'
    refresh_token: '{{ na_cloudmanager_info_refresh_token_01 }}'
    gather_subsets: '{{ na_cloudmanager_info_gather_subsets_01  | default(omit)  }}'
  register: results
