---
- name: Running command na_cloudmanager_info
  na_cloudmanager_info:
    client_id: '{{ na_cloudmanager_info_client_id_01 }}'
    environment: '{{ na_cloudmanager_info_environment_01  | default(omit)  }}'
    feature_flags: '{{ na_cloudmanager_info_feature_flags_01  | default(omit)  }}'
    gather_subsets: '{{ na_cloudmanager_info_gather_subsets_01  | default(omit)  }}'
    refresh_token: '{{ na_cloudmanager_info_refresh_token_01  | default(omit)  }}'
    sa_client_id: '{{ na_cloudmanager_info_sa_client_id_01  | default(omit)  }}'
    sa_secret_key: '{{ na_cloudmanager_info_sa_secret_key_01  | default(omit)  }}'
  register: results
