---
- name: Running command na_cloudmanager_cvo_azure
  na_cloudmanager_cvo_azure:
    cidr: '{{ na_cloudmanager_cvo_azure_cidr_01 }}'
    client_id: '{{ na_cloudmanager_cvo_azure_client_id_01 }}'
    location: '{{ na_cloudmanager_cvo_azure_location_01 }}'
    name: '{{ na_cloudmanager_cvo_azure_name_01 }}'
    subnet_id: '{{ na_cloudmanager_cvo_azure_subnet_id_01 }}'
    subscription_id: '{{ na_cloudmanager_cvo_azure_subscription_id_01 }}'
    svm_password: '{{ na_cloudmanager_cvo_azure_svm_password_01 }}'
    vnet_id: '{{ na_cloudmanager_cvo_azure_vnet_id_01 }}'
    allow_deploy_in_existing_rg: '{{ na_cloudmanager_cvo_azure_allow_deploy_in_existing_rg_01  | default(omit)  }}'
    azure_tag: '{{ na_cloudmanager_cvo_azure_azure_tag_01  | default(omit)  }}'
    backup_volumes_to_cbs: '{{ na_cloudmanager_cvo_azure_backup_volumes_to_cbs_01  | default(omit)  }}'
    capacity_tier: '{{ na_cloudmanager_cvo_azure_capacity_tier_01  | default(omit)  }}'
    cloud_provider_account: '{{ na_cloudmanager_cvo_azure_cloud_provider_account_01  | default(omit)  }}'
    data_encryption_type: '{{ na_cloudmanager_cvo_azure_data_encryption_type_01  | default(omit)  }}'
    disk_size: '{{ na_cloudmanager_cvo_azure_disk_size_01  | default(omit)  }}'
    disk_size_unit: '{{ na_cloudmanager_cvo_azure_disk_size_unit_01  | default(omit)  }}'
    enable_compliance: '{{ na_cloudmanager_cvo_azure_enable_compliance_01  | default(omit)  }}'
    enable_monitoring: '{{ na_cloudmanager_cvo_azure_enable_monitoring_01  | default(omit)  }}'
    environment: '{{ na_cloudmanager_cvo_azure_environment_01  | default(omit)  }}'
    instance_type: '{{ na_cloudmanager_cvo_azure_instance_type_01  | default(omit)  }}'
    is_ha: '{{ na_cloudmanager_cvo_azure_is_ha_01  | default(omit)  }}'
    license_type: '{{ na_cloudmanager_cvo_azure_license_type_01  | default(omit)  }}'
    nss_account: '{{ na_cloudmanager_cvo_azure_nss_account_01  | default(omit)  }}'
    ontap_version: '{{ na_cloudmanager_cvo_azure_ontap_version_01  | default(omit)  }}'
    platform_serial_number_node1: '{{ na_cloudmanager_cvo_azure_platform_serial_number_node1_01  | default(omit)  }}'
    platform_serial_number_node2: '{{ na_cloudmanager_cvo_azure_platform_serial_number_node2_01  | default(omit)  }}'
    refresh_token: '{{ na_cloudmanager_cvo_azure_refresh_token_01  | default(omit)  }}'
    resource_group: '{{ na_cloudmanager_cvo_azure_resource_group_01  | default(omit)  }}'
    sa_client_id: '{{ na_cloudmanager_cvo_azure_sa_client_id_01  | default(omit)  }}'
    sa_secret_key: '{{ na_cloudmanager_cvo_azure_sa_secret_key_01  | default(omit)  }}'
    security_group_id: '{{ na_cloudmanager_cvo_azure_security_group_id_01  | default(omit)  }}'
    serial_number: '{{ na_cloudmanager_cvo_azure_serial_number_01  | default(omit)  }}'
    state: '{{ na_cloudmanager_cvo_azure_state_01  | default(omit)  }}'
    storage_type: '{{ na_cloudmanager_cvo_azure_storage_type_01  | default(omit)  }}'
    tier_level: '{{ na_cloudmanager_cvo_azure_tier_level_01  | default(omit)  }}'
    use_latest_version: '{{ na_cloudmanager_cvo_azure_use_latest_version_01  | default(omit)  }}'
    vnet_resource_group: '{{ na_cloudmanager_cvo_azure_vnet_resource_group_01  | default(omit)  }}'
    workspace_id: '{{ na_cloudmanager_cvo_azure_workspace_id_01  | default(omit)  }}'
    writing_speed_state: '{{ na_cloudmanager_cvo_azure_writing_speed_state_01  | default(omit)  }}'
  register: results
