---
- name: Running command na_elementsw_info
  na_elementsw_info:
    fail_on_error: '{{ opt_info_fail_on_error_01  | default(omit)  }}'
    fail_on_key_not_found: '{{ opt_info_fail_on_key_not_found_01  | default(omit)  }}'
    fail_on_record_not_found: '{{ opt_info_fail_on_record_not_found_01  | default(omit)  }}'
    filter: '{{ opt_info_filter_01  | default(omit)  }}'
    gather_subsets: '{{ opt_info_gather_subsets_01  | default(omit)  }}'
  register: results
