---
- name: Running command na_elementsw_ldap
  na_elementsw_ldap:
    authType: '{{ opt_ldap_authType_01  | default(omit)  }}'
    groupSearchBaseDn: '{{ opt_ldap_groupSearchBaseDn_01  | default(omit)  }}'
    groupSearchCustomFilter: '{{ opt_ldap_groupSearchCustomFilter_01  | default(omit)  }}'
    groupSearchType: '{{ opt_ldap_groupSearchType_01  | default(omit)  }}'
    searchBindDN: '{{ opt_ldap_searchBindDN_01  | default(omit)  }}'
    searchBindPassword: '{{ opt_ldap_searchBindPassword_01  | default(omit)  }}'
    serverURIs: '{{ opt_ldap_serverURIs_01  | default(omit)  }}'
    state: '{{ opt_ldap_state_01  | default(omit)  }}'
    userDNTemplate: '{{ opt_ldap_userDNTemplate_01  | default(omit)  }}'
    userSearchBaseDN: '{{ opt_ldap_userSearchBaseDN_01  | default(omit)  }}'
    userSearchFilter: '{{ opt_ldap_userSearchFilter_01  | default(omit)  }}'
  register: results
