---
- name: Running command na_elementsw_cluster_snmp
  na_elementsw_cluster_snmp:
    networks: '{{ opt_cluster_snmp_networks_01  | default(omit)  }}'
    snmp_v3_enabled: '{{ opt_cluster_snmp_snmp_v3_enabled_01  | default(omit)  }}'
    state: '{{ opt_cluster_snmp_state_01  | default(omit)  }}'
    usm_users: '{{ opt_cluster_snmp_usm_users_01  | default(omit)  }}'
  register: results
