---
- name: Running command na_elementsw_initiators
  na_elementsw_initiators:
    initiators: '{{ opt_initiators_initiators_01  | default(omit)  }}'
    state: '{{ opt_initiators_state_01  | default(omit)  }}'
  register: results
