---
- name: Running command na_elementsw_volume_pair
  na_elementsw_volume_pair:
    dest_account: '{{ req_volume_pair_dest_account_01 }}'
    dest_mvip: '{{ req_volume_pair_dest_mvip_01 }}'
    dest_volume: '{{ req_volume_pair_dest_volume_01 }}'
    src_account: '{{ req_volume_pair_src_account_01 }}'
    src_volume: '{{ req_volume_pair_src_volume_01 }}'
    dest_password: '{{ opt_volume_pair_dest_password_01  | default(omit)  }}'
    dest_username: '{{ opt_volume_pair_dest_username_01  | default(omit)  }}'
    mode: '{{ opt_volume_pair_mode_01  | default(omit)  }}'
    state: '{{ opt_volume_pair_state_01  | default(omit)  }}'
  register: results
