---
- name: Running command na_um_list_volumes
  na_um_list_volumes:
    feature_flags: '{{ na_um_list_volumes_feature_flags_01  | default(omit)  }}'
    max_records: '{{ na_um_list_volumes_max_records_01  | default(omit)  }}'
  register: results
