---
- name: Running command na_sg_grid_gateway
  na_sg_grid_gateway:
    api_url: "{{{{ sg_api_url }}}}"
    auth_token: "{{{{ sg_auth_token }}}}"
    validate_certs: "{{{{ sg_validate_certs | default(false) }}}}"
    binding_mode: '{{ na_sg_grid_gateway_binding_mode_01  | default(omit)  }}'
    ca_bundle: '{{ na_sg_grid_gateway_ca_bundle_01  | default(omit)  }}'
    default_service_type: '{{ na_sg_grid_gateway_default_service_type_01  | default(omit)  }}'
    display_name: '{{ na_sg_grid_gateway_display_name_01  | default(omit)  }}'
    enable_ipv4: '{{ na_sg_grid_gateway_enable_ipv4_01  | default(omit)  }}'
    enable_ipv6: '{{ na_sg_grid_gateway_enable_ipv6_01  | default(omit)  }}'
    gateway_id: '{{ na_sg_grid_gateway_gateway_id_01  | default(omit)  }}'
    ha_groups: '{{ na_sg_grid_gateway_ha_groups_01  | default(omit)  }}'
    node_interfaces: '{{ na_sg_grid_gateway_node_interfaces_01  | default(omit)  }}'
    private_key: '{{ na_sg_grid_gateway_private_key_01  | default(omit)  }}'
    secure: '{{ na_sg_grid_gateway_secure_01  | default(omit)  }}'
    server_certificate: '{{ na_sg_grid_gateway_server_certificate_01  | default(omit)  }}'
    state: '{{ na_sg_grid_gateway_state_01  | default(omit)  }}'
  register: results
