---
- name: Running command na_sg_org_container
  na_sg_org_container:
    api_url: "{{{{ sg_api_url }}}}"
    auth_token: "{{{{ sg_auth_token }}}}"
    validate_certs: "{{{{ sg_validate_certs | default(false) }}}}"
    name: '{{ na_sg_org_container_name_01 }}'
    compliance: '{{ na_sg_org_container_compliance_01  | default(omit)  }}'
    region: '{{ na_sg_org_container_region_01  | default(omit)  }}'
    state: '{{ na_sg_org_container_state_01  | default(omit)  }}'
  register: results
