---
- name: Running command na_sg_grid_certificate
  na_sg_grid_certificate:
    api_url: "{{{{ sg_api_url }}}}"
    auth_token: "{{{{ sg_auth_token }}}}"
    validate_certs: "{{{{ sg_validate_certs | default(false) }}}}"
    type: '{{ na_sg_grid_certificate_type_01 }}'
    ca_bundle: '{{ na_sg_grid_certificate_ca_bundle_01  | default(omit)  }}'
    private_key: '{{ na_sg_grid_certificate_private_key_01  | default(omit)  }}'
    server_certificate: '{{ na_sg_grid_certificate_server_certificate_01  | default(omit)  }}'
    state: '{{ na_sg_grid_certificate_state_01  | default(omit)  }}'
  register: results
