---
- name: Running command na_sg_grid_identity_federation
  na_sg_grid_identity_federation:
    api_url: "{{{{ sg_api_url }}}}"
    auth_token: "{{{{ sg_auth_token }}}}"
    validate_certs: "{{{{ sg_validate_certs | default(false) }}}}"
    base_group_dn: '{{ na_sg_grid_identity_federation_base_group_dn_01  | default(omit)  }}'
    base_user_dn: '{{ na_sg_grid_identity_federation_base_user_dn_01  | default(omit)  }}'
    ca_cert: '{{ na_sg_grid_identity_federation_ca_cert_01  | default(omit)  }}'
    ldap_group_id_attribute: '{{ na_sg_grid_identity_federation_ldap_group_id_attribute_01  | default(omit)  }}'
    ldap_group_uuid_attribute: '{{ na_sg_grid_identity_federation_ldap_group_uuid_attribute_01  | default(omit)  }}'
    ldap_service_type: '{{ na_sg_grid_identity_federation_ldap_service_type_01  | default(omit)  }}'
    ldap_user_id_attribute: '{{ na_sg_grid_identity_federation_ldap_user_id_attribute_01  | default(omit)  }}'
    ldap_user_uuid_attribute: '{{ na_sg_grid_identity_federation_ldap_user_uuid_attribute_01  | default(omit)  }}'
    state: '{{ na_sg_grid_identity_federation_state_01  | default(omit)  }}'
    tls: '{{ na_sg_grid_identity_federation_tls_01  | default(omit)  }}'
    type: '{{ na_sg_grid_identity_federation_type_01  | default(omit)  }}'
  register: results
