---
- name: Running command nac_sg_grid_regions
  nac_sg_grid_regions:
    api_url: "{{ sg_api_url }}"
    auth_token: "{{ sg_auth_token }}"
    validate_certs: "{{ sg_validate_certs | default(false) }}"
    regions: '{{ req_sg_regions_regions_01 }}'
    state: '{{ req_sg_regions_state_01 }}'
  register: results
