---
- name: Running command na_um_volumes_info
  na_um_volumes_info:
    feature_flags: '{{ na_um_volumes_info_feature_flags_01  | default(omit)  }}'
    max_records: '{{ na_um_volumes_info_max_records_01  | default(omit)  }}'
  register: results
