---
- name: Running command na_ontap_kerberos_realm
  na_ontap_kerberos_realm:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username  | default(omit) }}"
    password: "{{ netapp_password  | default(omit) }}"
    cert_filepath: "{{ netapp_cert_filepath  | default(omit) }}"
    key_filepath: "{{ netapp_key_filepath  | default(omit) }}"
    https: "{{ netapp_https | default(true) }}"
    port: "{{ netapp_port  | default(omit) }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    http_port: "{{ opt_lun_map_http_port_01  | default(omit) }}"
    ontapi: "{{ opt_lun_map_ontapi_01  | default(omit) }}"
    use_rest: "{{ opt_lun_map_use_rest_01  | default(omit) }}"
    realm: '{{ req_kerberos_realm_realm_01 }}'
    vserver: '{{ req_kerberos_realm_vserver_01 }}'
    ad_server_ip: '{{ opt_kerberos_realm_ad_server_ip_01  | default(omit) }}'
    ad_server_name: '{{ opt_kerberos_realm_ad_server_name_01  | default(omit) }}'
    admin_server_ip: '{{ opt_kerberos_realm_admin_server_ip_01  | default(omit) }}'
    admin_server_port: '{{ opt_kerberos_realm_admin_server_port_01  | default(omit) }}'
    clock_skew: '{{ opt_kerberos_realm_clock_skew_01  | default(omit) }}'
    comment: '{{ opt_kerberos_realm_comment_01  | default(omit) }}'
    feature_flags: '{{ opt_kerberos_realm_feature_flags_01  | default(omit) }}'
    kdc_ip: '{{ opt_kerberos_realm_kdc_ip_01  | default(omit) }}'
    kdc_port: '{{ opt_kerberos_realm_kdc_port_01  | default(omit) }}'
    kdc_vendor: '{{ opt_kerberos_realm_kdc_vendor_01  | default(omit) }}'
    pw_server_ip: '{{ opt_kerberos_realm_pw_server_ip_01  | default(omit) }}'
    pw_server_port: '{{ opt_kerberos_realm_pw_server_port_01  | default(omit) }}'
    state: '{{ opt_kerberos_realm_state_01  | default(omit) }}'
  register: results
