---
- name: Running command na_ontap_node
  na_ontap_node:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username  | default(omit) }}"
    password: "{{ netapp_password  | default(omit) }}"
    cert_filepath: "{{ netapp_cert_filepath  | default(omit) }}"
    key_filepath: "{{ netapp_key_filepath  | default(omit) }}"
    https: "{{ netapp_https | default(true) }}"
    port: "{{ netapp_port  | default(omit) }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    http_port: "{{ opt_lun_map_http_port_01  | default(omit) }}"
    ontapi: "{{ opt_lun_map_ontapi_01  | default(omit) }}"
    use_rest: "{{ opt_lun_map_use_rest_01  | default(omit) }}"
    name: '{{ req_node_name_01 }}'
    asset_tag: '{{ opt_node_asset_tag_01  | default(omit) }}'
    feature_flags: '{{ opt_node_feature_flags_01  | default(omit) }}'
    from_name: '{{ opt_node_from_name_01  | default(omit) }}'
    location: '{{ opt_node_location_01  | default(omit) }}'
  register: results
