---
- name: Running command na_ontap_service_policy
  na_ontap_service_policy:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username  | default(omit)  }}"
    password: "{{ netapp_password  | default(omit)  }}"
    cert_filepath: "{{ netapp_cert_filepath  | default(omit)  }}"
    key_filepath: "{{ netapp_key_filepath  | default(omit)  }}"
    https: "{{ netapp_https | default(true) }}"
    port: "{{ netapp_port  | default(omit)  }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    http_port: "{{ opt_lun_map_http_port_01  | default(omit)  }}"
    ontapi: "{{ opt_lun_map_ontapi_01  | default(omit)  }}"
    use_rest: "{{ opt_lun_map_use_rest_01  | default(omit)  }}"
    name: '{{ req_service_policy_name_01 }}'
    feature_flags: '{{ opt_service_policy_feature_flags_01  | default(omit)  }}'
    ipspace: '{{ opt_service_policy_ipspace_01  | default(omit)  }}'
    scope: '{{ opt_service_policy_scope_01  | default(omit)  }}'
    services: '{{ opt_service_policy_services_01  | default(omit)  }}'
    state: '{{ opt_service_policy_state_01  | default(omit)  }}'
    vserver: '{{ opt_service_policy_vserver_01  | default(omit)  }}'
  register: results
