---
- name: Running command na_ontap_security_config
  na_ontap_security_config:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username  | default(omit)  }}"
    password: "{{ netapp_password  | default(omit)  }}"
    cert_filepath: "{{ netapp_cert_filepath  | default(omit)  }}"
    key_filepath: "{{ netapp_key_filepath  | default(omit)  }}"
    https: "{{ netapp_https | default(true) }}"
    port: "{{ netapp_port  | default(omit)  }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    http_port: "{{ opt_lun_map_http_port_01  | default(omit)  }}"
    ontapi: "{{ opt_lun_map_ontapi_01  | default(omit)  }}"
    use_rest: "{{ opt_lun_map_use_rest_01  | default(omit)  }}"
    feature_flags: '{{ opt_security_config_feature_flags_01  | default(omit)  }}'
    is_fips_enabled: '{{ opt_security_config_is_fips_enabled_01  | default(omit)  }}'
    name: '{{ opt_security_config_name_01  | default(omit)  }}'
    supported_ciphers: '{{ opt_security_config_supported_ciphers_01  | default(omit)  }}'
    supported_protocols: '{{ opt_security_config_supported_protocols_01  | default(omit)  }}'
  register: results
