---
- name: Running command na_ontap_interface
  na_ontap_interface:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username  | default(omit) }}"
    password: "{{ netapp_password  | default(omit) }}"
    cert_filepath: "{{ netapp_cert_filepath  | default(omit) }}"
    key_filepath: "{{ netapp_key_filepath  | default(omit) }}"
    https: "{{ netapp_https | default(true) }}"
    port: "{{ netapp_port  | default(omit) }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    http_port: "{{ opt_lun_map_http_port_01  | default(omit) }}"
    ontapi: "{{ opt_lun_map_ontapi_01  | default(omit) }}"
    use_rest: "{{ opt_lun_map_use_rest_01  | default(omit) }}"
    interface_name: '{{ req_interface_interface_name_01 }}'
    vserver: '{{ req_interface_vserver_01 }}'
    address: '{{ opt_interface_address_01  | default(omit) }}'
    admin_status: '{{ opt_interface_admin_status_01  | default(omit) }}'
    current_node: '{{ opt_interface_current_node_01  | default(omit) }}'
    current_port: '{{ opt_interface_current_port_01  | default(omit) }}'
    dns_domain_name: '{{ opt_interface_dns_domain_name_01  | default(omit) }}'
    failover_group: '{{ opt_interface_failover_group_01  | default(omit) }}'
    failover_policy: '{{ opt_interface_failover_policy_01  | default(omit) }}'
    feature_flags: '{{ opt_interface_feature_flags_01  | default(omit) }}'
    firewall_policy: '{{ opt_interface_firewall_policy_01  | default(omit) }}'
    force_subnet_association: '{{ opt_interface_force_subnet_association_01  | default(omit) }}'
    home_node: '{{ opt_interface_home_node_01  | default(omit) }}'
    home_port: '{{ opt_interface_home_port_01  | default(omit) }}'
    is_auto_revert: '{{ opt_interface_is_auto_revert_01  | default(omit) }}'
    is_dns_update_enabled: '{{ opt_interface_is_dns_update_enabled_01  | default(omit) }}'
    is_ipv4_link_local: '{{ opt_interface_is_ipv4_link_local_01  | default(omit) }}'
    listen_for_dns_query: '{{ opt_interface_listen_for_dns_query_01  | default(omit) }}'
    netmask: '{{ opt_interface_netmask_01  | default(omit) }}'
    protocols: '{{ opt_interface_protocols_01  | default(omit) }}'
    role: '{{ opt_interface_role_01  | default(omit) }}'
    service_policy: '{{ opt_interface_service_policy_01  | default(omit) }}'
    state: '{{ opt_interface_state_01  | default(omit) }}'
    subnet_name: '{{ opt_interface_subnet_name_01  | default(omit) }}'
  register: results
