---
- name: Running command na_ontap_publickey
  na_ontap_publickey:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username  | default(omit)  }}"
    password: "{{ netapp_password  | default(omit)  }}"
    cert_filepath: "{{ netapp_cert_filepath  | default(omit)  }}"
    key_filepath: "{{ netapp_key_filepath  | default(omit)  }}"
    https: "{{ netapp_https | default(true) }}"
    port: "{{ netapp_port  | default(omit)  }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    http_port: "{{ opt_lun_map_http_port_01  | default(omit)  }}"
    ontapi: "{{ opt_lun_map_ontapi_01  | default(omit)  }}"
    use_rest: "{{ opt_lun_map_use_rest_01  | default(omit)  }}"
    account: '{{ req_publickey_account_01 }}'
    comment: '{{ opt_publickey_comment_01  | default(omit)  }}'
    delete_all: '{{ opt_publickey_delete_all_01  | default(omit)  }}'
    feature_flags: '{{ opt_publickey_feature_flags_01  | default(omit)  }}'
    index: '{{ opt_publickey_index_01  | default(omit)  }}'
    public_key: '{{ opt_publickey_public_key_01  | default(omit)  }}'
    state: '{{ opt_publickey_state_01  | default(omit)  }}'
    vserver: '{{ opt_publickey_vserver_01  | default(omit)  }}'
  register: results
