---
- name: Running command na_ontap_ucadapter
  na_ontap_ucadapter:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username | default(omit) }}"
    password: "{{ netapp_password | default(omit) }}"
    cert_filepath: "{{ netapp_cert_filepath | default(omit) }}"
    key_filepath: "{{ netapp_key_filepath | default(omit) }}"
    https: "{{ netapp_https | default(true) }}"
    port: "{{ netapp_port | default(omit) }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    http_port: "{{ opt_lun_map_http_port_01 | default(omit) }}"
    ontapi: "{{ opt_lun_map_ontapi_01 | default(omit) }}"
    use_rest: "{{ opt_lun_map_use_rest_01 | default(omit) }}"
    adapter_name: '{{ req_ucadapter_adapter_name_01 }}'
    node_name: '{{ req_ucadapter_node_name_01 }}'
    feature_flags: '{{ opt_ucadapter_feature_flags_01 | default(omit) }}'
    mode: '{{ opt_ucadapter_mode_01 | default(omit) }}'
    pair_adapters: '{{ opt_ucadapter_pair_adapters_01 | default(omit) }}'
    state: '{{ opt_ucadapter_state_01 | default(omit) }}'
    type: '{{ opt_ucadapter_type_01 | default(omit) }}'
  register: results
