---
- name: Running command na_ontap_firewall_policy
  na_ontap_firewall_policy:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username  | default(omit) }}"
    password: "{{ netapp_password  | default(omit) }}"
    cert_filepath: "{{ netapp_cert_filepath  | default(omit) }}"
    key_filepath: "{{ netapp_key_filepath  | default(omit) }}"
    https: "{{ netapp_https | default(true) }}"
    port: "{{ netapp_port  | default(omit) }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    http_port: "{{ opt_lun_map_http_port_01  | default(omit) }}"
    ontapi: "{{ opt_lun_map_ontapi_01  | default(omit) }}"
    use_rest: "{{ opt_lun_map_use_rest_01  | default(omit) }}"
    allow_list: '{{ opt_firewall_policy_allow_list_01  | default(omit) }}'
    enable: '{{ opt_firewall_policy_enable_01  | default(omit) }}'
    feature_flags: '{{ opt_firewall_policy_feature_flags_01  | default(omit) }}'
    logging: '{{ opt_firewall_policy_logging_01  | default(omit) }}'
    node: '{{ opt_firewall_policy_node_01  | default(omit) }}'
    policy: '{{ opt_firewall_policy_policy_01  | default(omit) }}'
    service: '{{ opt_firewall_policy_service_01  | default(omit) }}'
    state: '{{ opt_firewall_policy_state_01  | default(omit) }}'
    vserver: '{{ opt_firewall_policy_vserver_01  | default(omit) }}'
  register: results
